### ISSUE TITLE
waitFor not available in component-tester

### ISSUE THREAD

**Issue by cehoffman** [aurelia/testing#61] opened 2017-03-22 18:42 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|

* **Node Version:**
7.7.2

* **NPM Version:**
yarn 0.22

* **JSPM OR Webpack AND Version**
JSPM 0.16.52

* **Browser:**
Chrome 55

* **Language:**
ES2015

**Current behavior:**
Trying to use `waitForElement` results in `waitFor is not defined` error.

**Expected/desired behavior:**
Works as advertised and waits for the elements.

* **What is the expected behavior?**
No error

* **What is the motivation / use case for changing the behavior?**
Function doesn't work as released.

**Comment by MeirionHughes** [comment] 2017-03-22 19:05
duplicate of https://github.com/aurelia/testing/issues/59

I believe this https://github.com/aurelia/testing/pull/60 will fix it. Don't think it is published yet.

**Closed as completed by MeirionHughes** 2017-03-22 19:05 UTC
Labels: duplicate
